version: "3.8"

services:
  localstack:
    image: localstack/localstack:0.10.1.2
    container_name: mangodeck-localstack
    networks:
      - localstack-net
    ports:
      - "10.0.0.17:53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      # - "${PORT_WEB_UI-4566}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-lambda,sqs,sns,apigateway,dynamodb,s3,cognito}
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse}
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      - DEBUG=${DEBUG-1}
      - DOCKER_HOST=unix:///var/run/docker.sock
      # - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY-}
      # - HOST_TMP_FOLDER=${TMPDIR}
      # - PORT_WEB_UI=${PORT_WEB_UI-8080}
    volumes:
      - "${TMPDIR-./localstack:/tmp/localstack}"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
    env_file:
      - .env

  test-lambda:
    image: test-lambda:latest
    # ports:
    # - "9001:9001"
    build:
      context: .
    networks:
      - localstack-net

networks:
  localstack-net:
    driver: bridge
    name: localstack-net
